### ISSUE TITLE
AttributeErrors when calling the plot function

### ISSUE THREAD

**Issue by mueller-seb** [bungun/conrad#2]
After installing appropriate versions of the python libraries there are still occurring some errors when executing the example files with both Python 2.7 and 3.5.
The remaining errors concern the plotting parts and are caused by missing attributes. I'm not a Python expert, but indeed these attributes seem not to be defined inside the respective class definitions.

**1.) branch 'main'**
In hello_world.py, Basic.py, DVH_Constraints.py and Prescription_based.py with Python 2.7
```
    graphics.plot(run)
  File "/home/xxx/.local/lib/python2.7/site-packages/conrad-0.0.2-py2.7.egg/conrad/visualization/plot/plotter.py", line 301, in plot
    if second_pass and data['exact'] is not None:
TypeError: 'RunRecord' object has no attribute '__getitem__'
```

In hello_world.py, Basic.py, DVH_Constraints.py and Prescription_based.py with Python 3.5
```
    graphics.plot(run)
  File "/home/xxx/conrad/conrad-env/lib/python3.5/site-packages/conrad-0.0.2-py3.5.egg/conrad/visualization/plot/plotter.py", line 301, in plot
    if second_pass and data['exact'] is not None:
TypeError: 'RunRecord' object is not subscriptable
```

In plotting_demo.py with both Python 2.7 and 3.5
```
Traceback (most recent call last):
  File "plotting_demo.py", line 131, in <module>
    demo(basepath=basepath)
  File "plotting_demo.py", line 14, in demo
    graphics.dvh_plot.autoset_series_colors(colormap='rainbow')
AttributeError: 'DVHPlot' object has no attribute 'autoset_series_colors'
```

Another attribute error occuring in Basic.py can be solved by introducing an auxilliary matrix valued variable before the for loop and saving the result in the DoseMatrix type matrix dose_matrix after the iteration, like in hello_world.py:

Basic.py with Python 2.7
```
Traceback (most recent call last):
  File "Basic.py", line 49, in <module>
    case.physics.dose_matrix[i, :] *= FACTOR
TypeError: 'DoseMatrix' object has no attribute '__getitem__'
```

Basic.py with Python 3.5
```
Traceback (most recent call last):
  File "Basic.py", line 49, in <module>
    case.physics.dose_matrix[i, :] *= FACTOR
TypeError: 'DoseMatrix' object is not subscriptable
```

**2.) branch 'cvxpy_1.0'**
Basic.py with Python 3.7
```
Traceback (most recent call last):
  File "Basic.py", line 71, in <module>
    graphics.plot(run)
  File "/home/sebastian/conrad/conrad-env/lib/python3.7/site-packages/conrad-0.0.2-py3.7.egg/conrad/visualization/plot/plotter.py", line 309, in plot
    self.dvh_set = data
  File "/home/sebastian/conrad/conrad-env/lib/python3.7/site-packages/conrad-0.0.2-py3.7.egg/conrad/visualization/plot/plotter.py", line 105, in dvh_set
    self.__dvh_set = PlanDVHGraph(self.filter_data(data))
  File "/home/sebastian/conrad/conrad-env/lib/python3.7/site-packages/conrad-0.0.2-py3.7.egg/conrad/visualization/plot/plotter.py", line 192, in filter_data
    iterator = data if isinstance(data, PlanGraphBase) else list(data.items())
AttributeError: 'numpy.ndarray' object has no attribute 'items'
```

**Comment by mueller-seb** [comment]
Addition: TypeError bugs in master branch were fixed in the cvxpy_1.0 branch. The plot function has to be called by 

```
status, run = case.plan()
graphics = CasePlotter(case)
plan_data = case.plotting_data()
graphics.plot(plan_data, plotfile='plotfile.png')
```
according to the test files. The example files were deprecated (see my fork for working examples).

EDIT1
After debugging Case.plan it is also possible to call the plot function by
```
status, run = case.plan()
graphics = CasePlotter(case)
graphics.plot(run.plotting_data, plotfile='plotfile.png')
```
